apiVersion: apps/v1 
kind: Deployment
metadata:
  name: karthik-demoapp
  labels: 
     app: regapp2

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp2

  template:
    metadata:
      labels:
        app: regapp2
    spec:
      containers:
      - name: regapp
        image: hemanth1211/regapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
